#+title: Japanese Configuration
Follow along if you are a Japanese Learner.

** Kagome (Japanese morphological analyzer)
#+begin_src sh
go install github.com/ikawaha/kagome/v2@latest
#+end_src

** yomichan-jlpt-vocab (An Modified Japanese Tokenizer and Japanese to English offline dictionary)
1. Compile the database, it is very easy, only three commands, no external
   python dependencies are involved. Also, it is a very small dictionary which
   only has JLPT words (14540 items). A file ~japanese.db~ will be generated.
    #+begin_src sh
    git clone https://github.com/chenyanming/yomichan-jlpt-vocab
    cd yomichan-jlpt-vocab
    python make_dictionary_db.py
    #+end_src
2. Set ~paw-jlpt-db~ and point to the location of ~japanese.db~.
3. PC: Download =mecap= and =unidic-lite= or ~janome~
    #+begin_src sh
    pip install mecab-python3
    pip install unidic-lite
    # pip install janome # You can also use janome instead
    #+end_src
4. Android: Download =janome= 
    #+begin_src sh
    pkg install tur-repo # https://github.com/termux-user-repository/tur 
    pkg install python3.10 # install python 3.10
    pip3.10 install janome # janome is much easier to install on Android
    #+end_src
5. Setup ~paw-python-program~ if necessary, if the pip module is installed with
   different python version, for android, set it to =python3.10=

6. Enable ~paw-annotation-show-unknown-words-p~
   1. Tweak ~paw-jlpt-tags~, part of or all among ~"n5 n4 n3 n2 n1"~
   2. Add words to known words file
      + Setup ~paw-jlpt-known-words-files~ and ~paw-jlpt-default-known-words-file~,
        for example, I have two files, one is csv file downloaded from somewhere,
        the other is a plain text maintained manually.
        #+begin_src elisp
       (setq paw-jlpt-known-words-files `(,(expand-file-name "japanese.txt" org-directory)))
       (setq paw-jlp-default-known-words-file (expand-file-name "japanese.txt" org-directory))
        #+end_src

** Text wordlists or dictionaries
1. You can also disable ~paw-annotation-show-unknown-words-p~, and use your
   personal wordlist files (csv/txt file dictionaries) instead, by setting
   ~paw-jlpt-wordlist-files~.
   - csv file requirement: just make sure first column is the word. Other
     columns will be automatically combined and separated by new line as
     explanation.
   - txt file requirement: the whole line should be the word, one line one word. 

You can think of ~paw-jlpt-wordlist-files~ are external text dictionaries. Paw will query the word with the first column of text dictionaries inside
~paw-jlpt-wordlist-files~, and use other columns as explanation. If no
explanation, it will use ~paw-jlpt-db~. 

You can also think of ~paw-jlpt-wordlist-files~ are editable wordlists. All words inside them will be highlighted (Blue by default) in the buffer that are enabled ~paw-annoatation-mode~, while words added into ~paw-db-file~ will be highlighted as Orange by default.
