name: Deploy Docusaurus Docs to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 如果还未初始化 Docusaurus，请先在本地执行：
      # npx create-docusaurus@latest website classic

      - name: Install Docusaurus dependencies
        run: |
          cd website
          npm ci

      - name: Convert README.org to Markdown
        run: |
          mkdir -p website/docs
          pandoc README.org -f org -t markdown -o website/docs/intro.md

      - name: Copy images and resources
        run: |
          mkdir -p website/static/images
          cp -r images/* website/static/images/

      - name: Build Docusaurus site
        run: |
          cd website
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
